### PR TITLE
Fix for Arm + Replaces `apt` with `apt-get`

### PR DESCRIPTION
**Pull request by weekOldRoadkill**
First time doing a pull request plz be nice! x3

### CODE REVIEW

**Comment by RouHim** [comment]
Closes #56

**Comment by RouHim** [comment]
The pipeline fails, please take a look into it.

**Review by RouHim — CHANGES_REQUESTED** [review]
The pipeline fails, please have a look.

**Comment by weekOldRoadkill** [comment]
nvm that just broke it even more

**Comment by RouHim** [comment]
You can test the arm64 build locally by running: `docker buildx build --platform linux/amd64,linux/arm64 -t rouhim/beammp-server:latest -f Containerfile .`

(requires docker buildx)

**Comment by weekOldRoadkill** [comment]
Should work now I hope!

**Comment by RouHim** [comment]
You need to request review again :)

**Comment by weekOldRoadkill** [comment]
How do I do that?

**Comment by RouHim** [comment]
I did it ;)

**Review by RouHim — APPROVED** [review]

**Pull request merged**
